# Apekey configuration

# Path to your XMonad configuration file, `xmonad.hs`
xmonad_config = "~/.config/xmonad/xmonad.hs"
# theme = 'Dark'

# [font]
# title_size = 22
# section_size = 16
# keybind_size = 16
# text_size = 16
# error_size = 16

