[package]
name = "apekey"
version = "0.1.0"
authors = ["pierre <dommerc.pierre@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
iced = { version = "0.4", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.0", features = ['env-filter'] }
clap = { version = "3.2.20", features = ["derive"] }
regex = "1.6.0"
lazy_static = "1.4.0"
dotenv = "0.15.0"
toml = "0.5"
anyhow = "1.0"
rgb = { version = "0.8", features = ["serde"] }
