[package]
name = "xmokey"
version = "0.1.0"
authors = ["pierre <dommerc.pierre@gmail.com>"]
edition = "2021"

[dependencies]
iced = { version = "0.4", features = ["tokio"] }
log = "0.4.17"
env_logger = "0.9.0"
clap = { version = "3.2.20", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
regex = "1.6.0"
lazy_static = "1.4.0"
